python:
   version: 3 # for unicode
   setup_py_install: true


site_name: Atelier Apache Spark
site_description: Cours et Travaux Pratiques pour se familiariser avec Apache Spark
site_author: Lilia Sfaxi
site_url: http://liliasfaxi.github.io/Atelier-Spark/

# Repository
repo_name: liliasfaxi/Atelier-Spark
repo_url: https://github.com/liliasfaxi/Atelier-Spark

# Copyright
copyright: 'Copyright &copy; 2019 - 2020 Lilia Sfaxi'

# Theme directory
plugins:
  - search
  - autolink_references:
        autolinks:
            - reference_prefix: AF-
              target_url: https://linear.com/AF-<num>
            - reference_prefix: PROJ-
              target_url: https://jiracloud.com/PROJ-<num> 
  - git-revision-date-localized:
      type: timeago
  - minify:
      minify_html: true

markdown_extensions:
  - admonition
  - meta
  - toc:
      permalink: true
      baselevel: 2
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

theme:
  name: material
  logo: "img/logo.png"
  palette:
    text: 'Ubuntu'
    code: 'Ubuntu Mono'
    primary: 'blue grey'
    accent: Amber
extra_css:
  - 'stylesheets/extra.css'
  - 'stylesheets/links.css'


# Page tree
pages:
   - 'index.md'
   - P1 - Introduction au Big Data: 'p1-big-data.md'
   - P2 - Introduction à Apache Spark: 'p2-spark.md'
   - P3 - Installation de Spark: 'p3-install.md'
   - P4 - RDD et Batch Processing avec Spark: 'p4-batch.md'
   - P5 - Spark SQL: 'p5-sql.md'
   - P6 - Spark Streaming: 'p6-stream.md'
   - P7 - Spark MLLib: 'p7-ml.md'
   - P8 - Spark GraphX: 'p8-graphx.md'



